steps:
  # Step 1: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/widifaizakhmad/slangtrapdev-notfintel', '.']

  # Step 2: Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/widifaizakhmad/slangtrapdev-notfintel']

  # Step 3: Deploy the container to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy slangtrapdev-notfintel \
          --image gcr.io/$PROJECT_ID/widifaizakhmad/slangtrapdev-notfintel \
          --region asia-southeast2 \
          --platform managed \
          --allow-unauthenticated

# Store images
#images:
 # - 'gcr.io/$PROJECT_ID/taufiksatrianugraha/fruitarians-model'
